[tool.poetry]
name = "hackathon24"
version = "0.1.0"
description = ""
authors = ["anton cornak", "lukas kostensky"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
openai = "~1.55.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"