[tool.poetry]
name = "hackathon-24"
version = "0.1.0"
description = ""
authors = ["anton cornak"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
openai = "^1.55.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"