[tool.poetry]
name = "py"
version = "0.1.0"
description = ""
authors = ["Martin Medvec <martin.medvec@visma.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
slack-bolt = "^1.21.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
